# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now you've gathered all the required skills needed to solve systems of linear equations. You saw why there was a need to calculate inverses of matrices, followed by matrix multiplication to figure out the values of unknown variables. 

The exercises in this lab present some problems that can be converted into a system of linear equations. 

## Objectives
You will be able to:

- Use matrix algebra and NumPy to solve a system of linear equations given a real-life example 
- Use NumPy's linear algebra solver to solve for systems of linear equations

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea were sold, for a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [4]:
# Create and solve the relevant system of equations
import numpy as np
# x will be price of coffee
# y will be price of tea
# 29x + 41y = 490
# 23x + 41y = 448

A = np.array([[29, 41], [23, 41]])
B = np.array([[490, 448]])

#calculate inverse of A
A_inv = np.linalg.inv(A)

#Check the shapes before transposing B
print('B Shape: {}'.format(B.shape))
# transpose
B = B.T
print("B Transposed Shape: {}".format(B.shape))
print(B)

# Calculate x 
X = A_inv.dot(B)
print(X)

#verify with linalg.solve

X_verify = np.linalg.solve(A,B)
print(X_verify)

B Shape: (1, 2)
B Transposed Shape: (2, 1)
[[490]
 [448]]
[[7.]
 [7.]]
[[7.]
 [7.]]


In [5]:
# Describe your result
# A bag of coffee is $7, as is a bag of tea.

## Exercise 2

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in the same music concert. 

How much was the admission for each child and adult?

In [9]:
# Create and solve the relevant system of equations

# 12c + 3a = 162 dollars
# 8c + 3a = 122 dollars

A = np.array([[12,3], [8,3]])
B = np.array([[162, 122]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)
# Get dot product with B transposed to calculate price of a child
X = A_inv.dot(B.T)
print(X)

# Verify with linalg.solve function
X_verify = np.linalg.solve(A, B.T)
print(X_verify)


[[10.]
 [14.]]
[[10.]
 [14.]]


In [ ]:
# Describe your result
# The child ticket cost $10, and the adult ticket cost $14

## Exercise 3

You want to make a soup containing tomatoes, carrots, and onions.

Suppose you don't know the exact mix to put in, but you know there are 7 individual pieces of vegetables, and there are twice as many tomatoes as onions, and that the 7 pieces of vegetables cost 5.25 USD in total. 
You also know that onions cost 0.5 USD each, tomatoes cost 0.75 USD and carrots cost 1.25 USD each.

Create a system of equations to find out exactly how many of each of the vegetables are in your soup.

In [11]:
# Create and solve the relevant system of equations
# keep the variables lined up (t+c+o)
# t + c + o = 7
# 0.75t + 1.25c + 0.5o = 5.25
# t = 2o OR t + 0c - 2o = 0

A = np.matrix([[1, 1, 1], [0.75, 1.25, 0.5], [1, 0, -2]])
B = np.matrix([[7,  5.25, 0]])

# Calculate inverse of A and Transpose B
A_inv = np.linalg.inv(A)
B_t = B.T
# Take dot product
X = A_inv.dot(B_t)
print(X)

#Verify with linalg solve function
X_verify = np.linalg.solve(A, B_t)
print(X_verify)

[[4.]
 [1.]
 [2.]]
[[4.]
 [1.]
 [2.]]


In [12]:
# Describe your result
# You need 4 tomatoes, 1 carrot, and 2 onion

## Exercise 4

A landlord owns 3 properties: a 1-bedroom, a 2-bedroom, and a 3-bedroom house. 

The total rent he receives is 1240 USD. 

He needs to make some repairs, where those repairs cost 10% of the 1-bedroom house’s rent. The 2-bedroom repairs cost 20% of the 2-bedroom rental price and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was 276 USD. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [14]:
# Create and solve the relevant system of equations
# onebdr + twobdr + threebdr = 3 properties
# onebdr + twobdr + threebdr = 1240
# .10onebdr + .20twobdr + .30threebdr = 276
# threebdr = 2onebdr OR -2onebdr + 0twobdr + 1threebdr = 0

A = np.matrix([[1, 1, 1], [0.10, 0.20, 0.30], [-2, 0, 1]])
B = np.matrix([[1240, 276, 0]])

A_inv = np.linalg.inv(A)
B_t = np.transpose(B)
X = A_inv.dot(B_t)
print(X)

#verify
X_verify = np.linalg.solve(A, B_t)
print(X_verify)

[[280.]
 [400.]
 [560.]]
[[280.]
 [400.]
 [560.]]


In [ ]:
# Describe your result
# the one bedroom rent is $280
# the two bedroom rent is $400
# the three bedroom rent is $560

## Summary
In this lab, you learned how to use NumPy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `solve()` function. You'll now take these skills forward and see how you can define a simple regression problem using linear algebra and solve it with Numpy. 